CREATE TABLE IF NOT EXISTS `HYORDERDETAIL` (
  `HYORDDID` int(100) NOT NULL AUTO_INCREMENT,
  `HYORDHID` int(100) NOT NULL ,
  `HYORDDLOTTERY` VARCHAR(3)  NOT NULL,
  `HYORDDTOP` decimal(60,5)   NULL,
  `HYORDDREVERSE` decimal(60,5)   NULL,
  `HYORDDUNDER` decimal(60,5)   NULL,
  PRIMARY KEY (`HYORDDID`)
);